<a href="https://colab.research.google.com/github/MarkowitzMx/Programacion-para-analitica-descriptiva-y-predictiva-2026/blob/main/Copy_of_S06_Actividad_02_ALGEBRALINEAL_MATRICULA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [16]:
# Importa la librería NumPy, que permite trabajar con arreglos (vectores/matrices)
# y realizar operaciones matemáticas de forma eficiente.

import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [17]:
# Crea un arreglo de NumPy (vector) llamado producto_A con 3 componentes numéricas.
producto_A = np.array([4.5, 3.2, 5.0])

#Crea un vector producto_B con 3 componentes, representando otro conjunto de valores.
producto_B = np.array([4.0, 2.8, 4.7])

#Crea un vector producto_C con 3 componentes.
producto_C = np.array([1.0, 5.0, 1.2])

# Imprime en pantalla los tres vectores para verificar que se crearon correctamente.
print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [18]:
# Tu código aquí

# Calcula la norma (magnitud o longitud) del vector producto_A usando la fórmula
# de la norma euclidiana: raíz cuadrada de la suma de los cuadrados de sus componentes.
# El resultado es un número escalar (float) y se guarda en norma_A.

norma_A = np.linalg.norm(producto_A)

# Calcula la norma euclidiana del vector producto_B, siguiendo el mismo procedimiento.
norma_B = np.linalg.norm(producto_B)

# Calcula la norma euclidiana del vector producto_C, siguiendo el mismo procedimiento.
norma_C = np.linalg.norm(producto_C)

#Imprime un texto descriptivo junto con el valor numérico de la norma de producto_A, producto_B y producto_C.
print("Norma de producto_A:", norma_A)
print("Norma de producto_B:", norma_B)
print("Norma de producto_C:", norma_C)

Norma de producto_A: 7.449161026585477
Norma de producto_B: 6.777167549942971
Norma de producto_C: 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [19]:
# Tu código aquí

# 1. Calcula el producto punto entre producto_A y producto_B
# El producto punto (dot product) mide cuánto "coinciden" dos vectores en dirección.
# Se calcula multiplicando componente a componente y sumando los resultados.
dot_AB = np.dot(producto_A, producto_B)

# Calcula el producto punto entre producto_A y producto_C, de la misma forma.
dot_AC = np.dot(producto_A, producto_C)

# Imprime los resultados de ambos productos punto.
print("1. Calculo del producto punto: producto_A y producto_B y el producto_A y producto_C")
print("Producto punto A·B:", dot_AB)
print("Producto punto A·C:", dot_AC)


# 2. Calcula el ángulo (en grados) entre producto_A y producto_B, y entre producto_A y producto_C

# La fórmula del coseno del ángulo entre dos vectores es:
# cos(θ) = (A · B) / (||A|| * ||B||)
# Primero calculamos el coseno del ángulo entre A y B usando el producto punto
# y las normas (magnitudes) de cada vector.

print( "2. Angulo (en grados) entre el producto_A y producto_B, y entre el producto_A y el producto_C")
cos_AB = dot_AB / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))

# Calculamos el coseno del ángulo entre A y C de la misma manera.
cos_AC = dot_AC / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))

# np.arccos() obtiene el ángulo en radianes a partir del coseno calculado.
# np.degrees() convierte ese ángulo de radianes a grados, que es más intuitivo de leer.
angulo_AB = np.degrees(np.arccos(cos_AB))
angulo_AC = np.degrees(np.arccos(cos_AC))

# Imprime los ángulos calculados entre los vectores.
print("Ángulo entre A y B (grados):", angulo_AB)
print("Ángulo entre A y C (grados):", angulo_AC)


# 3. Comparación: ¿cuál de los dos productos (B o C) es más similar a producto_A?
# El ángulo entre A y B es mucho más pequeño que el ángulo entre A y C,
# lo que indica que producto_B apunta en una dirección mucho más parecida
# a producto_A dentro del espacio de características (por ejemplo, calidad,
# precio, satisfacción, etc., según lo que representen las componentes).
# El ángulo es el indicador correcto para esta comparación porque mide la
# similitud en la DIRECCIÓN de los vectores, independientemente de su magnitud;
# es decir, compara la "proporción" entre las características de cada producto,
# no simplemente qué tan grandes son sus valores.
# Por lo tanto, producto_B es más similar a producto_A que producto_C.

1. Calculo del producto punto: producto_A y producto_B y el producto_A y producto_C
Producto punto A·B: 50.46
Producto punto A·C: 26.5
2. Angulo (en grados) entre el producto_A y producto_B, y entre el producto_A y el producto_C
Ángulo entre A y B (grados): 1.7745815839558179
Ángulo entre A y C (grados): 47.22509268261831


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [20]:
# Tu código aquí

# Normalizar un vector significa dividir cada componente entre su norma (magnitud),
# de manera que el vector resultante tenga la misma dirección pero magnitud (longitud) igual a 1.
# Fórmula: v_normalizado = v / ||v||

# Normaliza producto_A dividiendo cada componente entre su norma.
producto_A_norm = producto_A / np.linalg.norm(producto_A)

# Normaliza producto_B de la misma forma.
producto_B_norm = producto_B / np.linalg.norm(producto_B)

# Normaliza producto_C de la misma forma.
producto_C_norm = producto_C / np.linalg.norm(producto_C)

# Imprime los vectores normalizados (unitarios).
print("Vector normalizado A:", producto_A_norm)
print("Vector normalizado B:", producto_B_norm)
print("Vector normalizado C:", producto_C_norm)

# Verifica que la norma de cada vector normalizado sea igual a 1.
# Esto confirma que la normalización se realizó correctamente.
print("Norma de A normalizado:", np.linalg.norm(producto_A_norm))
print("Norma de B normalizado:", np.linalg.norm(producto_B_norm))
print("Norma de C normalizado:", np.linalg.norm(producto_C_norm))

Vector normalizado A: [0.60409488 0.42957858 0.67121653]
Vector normalizado B: [0.59021707 0.41315195 0.69350506]
Vector normalizado C: [0.19090089 0.95450444 0.22908106]
Norma de A normalizado: 1.0
Norma de B normalizado: 1.0
Norma de C normalizado: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [21]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [22]:
# Tu código aquí

# 1. Calcula M * P (elemento a elemento) y M @ P (multiplicación matricial)

# M * P realiza una multiplicación ELEMENTO A ELEMENTO (Hadamard),
# es decir, multiplica cada posición [i,j] de M con la misma posición [i,j] de P.
# Ambas matrices deben tener la misma forma (2x2 en este caso).
mult_elemento = M * P

# M @ P realiza la MULTIPLICACIÓN MATRICIAL tradicional (producto matricial),
# donde cada elemento resultante [i,j] es la suma de los productos de la
# fila i de M con la columna j de P (regla fila por columna).
mult_matricial = M @ P

# Imprime ambos resultados para compararlos.
print("M * P (elemento a elemento):")
print(mult_elemento)

print("M @ P (multiplicación matricial):")
print(mult_matricial)

# Explicación de por qué son distintos:
# M * P multiplica cada celda de forma independiente, sin combinar filas y columnas;
# el resultado solo depende de la posición [i,j] en ambas matrices.
# M @ P, en cambio, combina TODA una fila de M con TODA una columna de P
# (sumando productos), lo cual mezcla la información entre insumos/columnas.
# Al ser operaciones matemáticamente distintas, es normal (y esperado) que
# produzcan resultados diferentes, salvo en casos muy particulares (por ejemplo,
# si una de las matrices es la identidad).


# 2. Verifica que las formas sean compatibles y calcula P @ M

# Como M y P son ambas matrices 2x2, la multiplicación matricial es compatible
# en ambos órdenes (M @ P y P @ M), y el resultado también será 2x2.
# Sin embargo, la multiplicación de matrices NO es conmutativa en general,
# es decir, el orden de los factores SÍ afecta el resultado.
mult_matricial_PM = P @ M

# Imprime el resultado de P @ M.
print("P @ M (multiplicación matricial):")
print(mult_matricial_PM)

# Compara si M @ P es igual a P @ M.
# np.array_equal() verifica si dos arreglos tienen exactamente los mismos valores.
son_iguales = np.array_equal(mult_matricial, mult_matricial_PM)
print("¿M @ P es igual a P @ M?:", son_iguales)

# Conclusión: M @ P y P @ M NO dan el mismo resultado.
# Esto confirma que la multiplicación matricial NO es conmutativa:
# el orden en que se multiplican las matrices importa, porque cada producto
# combina filas con columnas de manera distinta según el orden de los factores.

M * P (elemento a elemento):
[[3. 0.]
 [0. 6.]]
M @ P (multiplicación matricial):
[[3.  2. ]
 [1.5 6. ]]
P @ M (multiplicación matricial):
[[3.  1.5]
 [2.  6. ]]
¿M @ P es igual a P @ M?: False


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [23]:
# Tu código aquí

# 1. Calcula el determinante de M usando np.linalg.det()
# El determinante es un valor escalar que indica si una matriz tiene inversa.
# Si el determinante es distinto de 0, la matriz es "invertible" (no singular).
# Si el determinante es 0, la matriz NO tiene inversa (es singular).
det_M = np.linalg.det(M)

# Imprime el determinante calculado.
print("Determinante de M:", det_M)

# Confirma si M tiene inversa comparando si el determinante es distinto de 0.
if det_M != 0:
    print("M tiene inversa, ya que su determinante es distinto de 0.")
else:
    print("M NO tiene inversa, ya que su determinante es igual a 0.")


# 2. Calcula la inversa de M usando np.linalg.inv()
# La inversa de una matriz M es otra matriz M_inv tal que M @ M_inv = Identidad.
M_inv = np.linalg.inv(M)

# Imprime la matriz inversa calculada.
print("Inversa de M:")
print(M_inv)


# 3. Verifica el resultado calculando M @ M_inv
# Si la inversa fue calculada correctamente, este producto debe dar
# (aproximadamente) la matriz identidad: unos en la diagonal y ceros fuera de ella.
# Se dice "aproximadamente" porque, por la naturaleza de los cálculos con
# números de punto flotante, pueden aparecer pequeños errores de redondeo
# (por ejemplo, 0.9999999999 en vez de 1, o -1e-17 en vez de 0).
verificacion = M @ M_inv

# Imprime el resultado de la verificación.
print("M @ M_inv (debe ser aprox. la identidad):")
print(verificacion)

Determinante de M: 5.000000000000001
M tiene inversa, ya que su determinante es distinto de 0.
Inversa de M:
[[ 0.6 -0.2]
 [-0.2  0.4]]
M @ M_inv (debe ser aprox. la identidad):
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [24]:
b = np.array([180, 300])

# Tu código aquí


# 1. Resuelve el sistema Mx = b usando np.linalg.solve()
# np.linalg.solve() encuentra el vector x que satisface la ecuación matricial Mx = b,
# de forma más eficiente y numéricamente estable que calcular la inversa manualmente
# (es decir, es preferible a hacer x = M_inv @ b).
x = np.linalg.solve(M, b)

# Imprime la solución encontrada.
print("Solución x (unidades necesarias de cada insumo):", x)


# 2. Verifica la solución multiplicando M @ x y comparando con b
# Si x es correcto, M @ x debe dar (aproximadamente) el mismo vector que b.
verificacion = M @ x

# Imprime el resultado de la verificación.
print("Verificación M @ x:", verificacion)

# Compara si el resultado coincide con b.
# Se usa np.allclose() en lugar de comparar con == directamente, ya que las
# operaciones con números de punto flotante pueden generar pequeñas diferencias
# de redondeo, y allclose() permite una tolerancia mínima para esas diferencias.
coincide = np.allclose(verificacion, b)
print("¿M @ x coincide con b?:", coincide)

Solución x (unidades necesarias de cada insumo): [48. 84.]
Verificación M @ x: [180. 300.]
¿M @ x coincide con b?: True


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [25]:
# Tu código aquí

# 1. Calcula la distancia euclidiana entre producto_A y producto_B, y entre producto_A y producto_C
# La distancia euclidiana mide qué tan "lejos" están dos vectores en el espacio,
# tomando en cuenta tanto su dirección como su magnitud (a diferencia del ángulo,
# que solo considera la dirección).
# Se calcula como la norma del vector diferencia: ||a - b||
distancia_AB = np.linalg.norm(producto_A - producto_B)
distancia_AC = np.linalg.norm(producto_A - producto_C)

# Imprime las distancias calculadas.
print("Distancia euclidiana entre A y B:", distancia_AB)
print("Distancia euclidiana entre A y C:", distancia_AC)


# 2. Calcula la similitud coseno entre los mismos pares
# La similitud coseno es el coseno del ángulo entre dos vectores, calculado como:
# similitud = (a · b) / (||a|| * ||b||)
# Su valor va de -1 a 1: mientras más cercano a 1, más parecida es la DIRECCIÓN
# de los vectores (independientemente de su magnitud).
similitud_AB = np.dot(producto_A, producto_B) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))
similitud_AC = np.dot(producto_A, producto_C) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))

# Imprime las similitudes coseno calculadas.
print("Similitud coseno entre A y B:", similitud_AB)
print("Similitud coseno entre A y C:", similitud_AC)


# 3. Conclusión con base en ambas métricas

# Determina cuál producto tiene menor distancia euclidiana a producto_A
# (menor distancia = más parecido en magnitud y dirección combinadas).
mas_cercano_distancia = "B" if distancia_AB < distancia_AC else "C"

# Determina cuál producto tiene mayor similitud coseno con producto_A
# (mayor similitud coseno = dirección más parecida).
mas_cercano_similitud = "B" if similitud_AB > similitud_AC else "C"

# Verifica si ambas métricas coinciden en el mismo producto como "más parecido".
coinciden = mas_cercano_distancia == mas_cercano_similitud

# Construye una conclusión en texto, integrando los resultados de ambas métricas.
conclusion = (
    f"Según la distancia euclidiana, el producto más cercano a producto_A es {mas_cercano_distancia} "
    f"(distancia A-B: {distancia_AB:.4f}, distancia A-C: {distancia_AC:.4f}). "
    f"Según la similitud coseno, el producto más parecido a producto_A es {mas_cercano_similitud} "
    f"(similitud A-B: {similitud_AB:.4f}, similitud A-C: {similitud_AC:.4f}). "
    f"{'Ambas métricas coinciden en que producto_' + mas_cercano_distancia + ' es el más parecido a producto_A.' if coinciden else 'Las métricas NO coinciden en su conclusión.'}"
)

# Imprime la conclusión final.
print(conclusion)

Distancia euclidiana entre A y B: 0.7071067811865476
Distancia euclidiana entre A y C: 5.470831746635972
Similitud coseno entre A y B: 0.9995203969214979
Similitud coseno entre A y C: 0.6791199021706347
Según la distancia euclidiana, el producto más cercano a producto_A es B (distancia A-B: 0.7071, distancia A-C: 5.4708). Según la similitud coseno, el producto más parecido a producto_A es B (similitud A-B: 0.9995, similitud A-C: 0.6791). Ambas métricas coinciden en que producto_B es el más parecido a producto_A.


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.